#include <Arduino.h>

const char commonRest[] PROGMEM = R"rawliteral(
(function(){
const d=document,W=window,q=i=>d.getElementById(i),F=(c,cb)=>fetch('/cmd='+c).then(r=>r.text()).then(t=>cb&&cb(null,t)).catch(e=>cb&&cb(e));
W.sendCommand=W.sendCommand||F;
let tmr;
function upd(){fetch('/cmd=GET_DEVICE_INFO').then(r=>r.text()).then(t=>{const v=t.split(','),ip=v[0],p1=v[1],p2=v[2],sw=v[3],D=+v[4]||0,h=+v[5]||0,m=+v[6]||0,s=+v[7]||0,st=v[8],up=D>0?`${D}d ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;const DIP=q('deviceIP');if(DIP)DIP.textContent=ip;const DPT=q('devicePorts');if(DPT)DPT.textContent=`${p1}, ${p2}`;const SW=q('swVersion');if(SW)SW.textContent=sw;const UP=q('uptime');if(UP)UP.textContent=up;const DS=q('deviceStatus');if(DS){DS.textContent=st;DS.className='device-info-value '+(st==='READY'?'status-ready':'status-fault');}}).catch(()=>{});} 
function tog(){const a=q('autoUpdate');if(!a)return;if(a.checked){if(tmr)clearInterval(tmr);tmr=setInterval(upd,5000);}else{if(tmr)clearInterval(tmr);}} 
W.toggleAutoUpdate=W.toggleAutoUpdate||tog;
function initSCPI(){const inp=q('scpiInput'),out=q('terminalOutput'),log=s=>{if(out){out.textContent+=s+'\n';out.scrollTop=out.scrollHeight;}};const send=()=>{if(!inp)return;const c=inp.value.trim();if(!c)return;log('>> '+c);F(c,(e,t)=>log(e?'Error: '+e.message:t));};const clr=()=>{if(out)out.textContent='SCPI Terminal Ready\n>> Type commands above and press Send or Enter\n>> \n';};const cp=c=>{if(inp){inp.value=c;inp.focus();}};const sb=q('sendScpiCommand');if(sb)sb.addEventListener('click',send);const cb=q('clearScpiTerminal');if(cb)cb.addEventListener('click',clr);if(inp)inp.addEventListener('keypress',e=>{if(e.key==='Enter')send();});W.copyToInput=W.copyToInput||cp;W.sendSCPICommand=W.sendSCPICommand||send;W.clearTerminal=W.clearTerminal||clr;W.handleEnter=W.handleEnter||function(e){if(e.key==='Enter')send();};}
function initADC(){const sel=q('adcSelector'),ch=q('channelControl'),rng=q('rangeSelector'),val=q('measurementValue'),raw=q('measurementRaw'),resp=q('response');if(!sel||!rng)return;const info={ONBOARD:{address:'0x48',location:'Onboard',channels:1},EXT1:{address:'0x48',location:'External (via MUX)',channels:0},EXT2:{address:'0x49',location:'External (via MUX)',channels:0}};const upI=a=>{const i=info[a],loc=q('infoLocation'),adr=q('infoAddress');if(loc)loc.textContent=i.location;if(adr)adr.textContent=i.address;};const upC=()=>{const a=sel.value;if(ch)ch.style.display=info[a].channels?'block':'none';upI(a);};const meas=()=>{const a=sel.value,r=rng.value;let c;if(a==='ONBOARD'){const cs=q('channelSelector');const k=cs?cs.value:'0';c=`ADC:MEAS:ONBOARD?${k},${r}`;}else c=`ADC:MEAS:${a}?${r}`;F(c,(e,t)=>{if(e){if(resp)resp.innerHTML='<strong>Fetch Error:</strong> '+e.message;return;}const p=(t||'').split(','),v=parseFloat(p[0]),rw=parseInt(p[1]);if(val)val.innerHTML=`${isFinite(v)?v.toFixed(4):'---.----'}<span class="measurement-unit">V</span>`;if(raw)raw.textContent='RAW: '+(isFinite(rw)?rw:'----');if(resp)resp.innerHTML='<strong>Command:</strong> '+c+'<br><strong>Response:</strong> '+t;});};sel.addEventListener('change',upC);const mb=d.querySelector('.measure-button');if(mb)mb.addEventListener('click',meas);upC();}
function initInfo(){const btn=q('getEramButton'),out=q('eramOutput'),sip=q('setIpButton'),ip=q('ipInput');if(btn)btn.addEventListener('click',()=>{if(out)out.textContent='Fetching ERAM data...\n';F('ERAM?',(e,t)=>{if(!out)return;if(e)out.textContent='Error: '+e.message+'\n';else{const v=(t||'').split(','),s='ERAM Constants:\n'+v.map((x,i)=>`[${String(i).padStart(2,'0')}]\t${x.trim()}`).join('\n');out.textContent=s;}out.scrollTop=out.scrollHeight;});});if(sip)sip.addEventListener('click',()=>{if(!ip)return;const x=ip.value.trim();if(!x)return alert('Please enter a valid IP address.');F('SET_IP '+x,(e,t)=>{if(e)alert('Error setting IP: '+e.message);else{alert('Response: '+t);const dip=q('deviceIP');if(dip)dip.textContent=x;}});});}
document.addEventListener('DOMContentLoaded',()=>{upd();tog();initSCPI();initADC();initInfo();});
})();
)rawliteral";